[package]
name = "libp2p-tls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = { version = "0.20.2", default-features = false, features = ["dangerous_configuration"] }
x509-parser = "0.13.0"
libp2p-core = { version = "0.36.0", path = "../../core" }
webpki = "0.22.0"
rcgen = "0.9.2"
yasna = "0.5.0"
ring = "0.16.20"
futures = { version = "0.3.24", default-features = false }
thiserror = "1.0.36"
futures-rustls = "0.22.2"
either = "1.8.0"

[dev-dependencies]
libp2p = { path = "../..", features = ["yamux"], default-features = false }
tokio = { version = "1.21.1", features = ["full"] }
